#!/bin/sh
echo "\"sed\"ing the php-fpm.conf"
sed -i -e "s/<UPLOAD_MAX_SIZE>/$UPLOAD_MAX_SIZE/g" /etc/php7/php-fpm.conf \
       -e "s/<MEMORY_LIMIT>/$MEMORY_LIMIT/g" /etc/php7/php-fpm.conf \
       -e "s/<DISPLAY_ERRORS>/$DISPLAY_ERRORS/g" /etc/php7/php-fpm.conf
echo "\"chown\"ing the php directories"
chown -R ${UID}:${GID} ${APPDIR} /var/log/php7
echo "running php"
su-exec ${UID}:${GID} php-fpm7
