#!/bin/sh
echo "\"sed\"ing the php-fpm.conf"

# DEFAULTS
PM_START_SERVERS=${PM_START_SERVERS:-2}
PM_MAX_CHILDREN=${PM_MAX_CHILDREN:-15}
PM_MAX_SPARE_SERVERS=${PM_MAX_SPARE_SERVERS:-6}
PM_MIN_SPARE_SERVERS=${PM_MIN_SPARE_SERVERS:-1}


sed -i -e "s/<UPLOAD_MAX_SIZE>/$UPLOAD_MAX_SIZE/g" /etc/php7/php-fpm.conf \
       -e "s/<PM_START_SERVERS>/$PM_START_SERVERS/g" /etc/php7/php-fpm.conf \
       -e "s/<PM_MAX_CHILDREN>/$PM_MAX_CHILDREN/g" /etc/php7/php-fpm.conf \
       -e "s/<PM_MAX_SPARE_SERVERS>/$PM_MAX_SPARE_SERVERS/g" /etc/php7/php-fpm.conf \
       -e "s/<PM_MIN_SPARE_SERVERS>/$PM_MIN_SPARE_SERVERS/g" /etc/php7/php-fpm.conf \
       -e "s/<MEMORY_LIMIT>/$MEMORY_LIMIT/g" /etc/php7/php-fpm.conf \
       -e "s/<DISPLAY_ERRORS>/$DISPLAY_ERRORS/g" /etc/php7/php-fpm.conf
echo "\"chown\"ing the php directories"
chown -R ${UID}:${GID} ${APPDIR} /var/log/php7
echo "running php"
su-exec ${UID}:${GID} php-fpm7
